import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content:[
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#171f33",
        "on-primary-container": "#340080",
        "surface-container-highest": "#2d3449",
        "on-primary-fixed-variant": "#5516be",
        "secondary-container": "#03b5d3",
        "on-secondary-fixed-variant": "#004e5c",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#00424e",
        "secondary": "#4cd7f6",
        "surface-container-lowest": "#060e20",
        "primary": "#d0bcff",
        "surface": "#0b1326",
        "tertiary-fixed": "#ffdad7",
        "on-tertiary-container": "#5c0008",
        "on-background": "#dae2fd",
        "surface-dim": "#0b1326",
        "outline": "#958ea0",
        "tertiary": "#ffb3ad",
        "on-primary-fixed": "#23005c",
        "on-secondary": "#003640",
        "surface-tint": "#d0bcff",
        "primary-fixed": "#e9ddff",
        "primary-container": "#a078ff",
        "surface-container-high": "#222a3d",
        "on-error": "#690005",
        "inverse-surface": "#dae2fd",
        "inverse-on-surface": "#283044",
        "error-container": "#93000a",
        "surface-variant": "#2d3449",
        "error": "#ffb4ab",
        "on-surface-variant": "#cbc3d7",
        "secondary-fixed": "#acedff",
        "secondary-fixed-dim": "#4cd7f6",
        "on-primary": "#3c0091",
        "on-surface": "#dae2fd",
        "tertiary-container": "#ff5451",
        "background": "#0b1326",
        "primary-fixed-dim": "#d0bcff",
        "tertiary-fixed-dim": "#ffb3ad",
        "outline-variant": "#494454",
        "on-tertiary-fixed-variant": "#930013",
        "inverse-primary": "#6d3bd7",
        "surface-container-low": "#131b2e",
        "on-tertiary-fixed": "#410004",
        "surface-bright": "#31394d",
        "on-tertiary": "#68000a",
        "on-secondary-fixed": "#001f26",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        grid_gutter: "20px",
        unit: "4px",
        collapsed_sidebar: "80px",
        section_margin: "32px",
        container_max_width: "1600px",
        sidebar_width: "260px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Spline Sans", "sans-serif"],
        "label-md": ["Spline Sans", "sans-serif"],
        "headline-md":["Spline Sans", "sans-serif"],
        "display-lg":["Spline Sans", "sans-serif"],
        "headline-lg": ["Spline Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm":["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-md":["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md":["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg":["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg":["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins:[
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries")
  ],
};
export default config;